[package]
name = "peerko"
version = "0.0.1"
edition = "2021"
authors = ["penumbra23"]

[dependencies]
clap = { version = "3.2.6", features = ["derive"] }
multiqueue = "0.3.2"
byteorder = "1.4.3"
crossterm = "0.24.0"
tui = "0.18.0"
unicode-width = "0.1.9"
crossbeam-channel = "0.5"
